apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testbed-role
  namespace: testbed-dev
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - get
  - list
  - create
