apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testbed-role-binding
  namespace: testbed-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: testbed-role
subjects:
- kind: ServiceAccount
  name: testbed-service-account
  namespace: testbed-dev
