apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbed-api-deployment
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testbed-api
  template:
    metadata:
      labels:
        app: testbed-api
      annotations:
        timestamp: "${TIMESTAMP}"
    spec:
      serviceAccountName: testbed-api-sa
      containers:
      - name: testbed-api
        image: ${DOCKER_REGISTRY}/moatless-testbed-api:${IMAGE_TAG}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: api-keys
          mountPath: /app/api_keys.json
          subPath: api_keys.json
        env:
        - name: KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: api-keys
        secret:
          secretName: testbed-api-keys-secret