apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbed-api-deployment
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testbed-api
  template:
    metadata:
      labels:
        app: testbed-api
    spec:
      serviceAccountName: testbed-api-sa
      containers:
      - name: testbed-api
        image: ${DOCKER_REGISTRY}/moatless-testbed-api:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "300Mi"
          limits:
            memory: "1Gi"
        volumeMounts:
        - name: api-keys
          mountPath: /app/api_keys.json
          subPath: api_keys.json
        env:
        - name: KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SWEBENCH_DOCKER_REGISTRY
          value: "${SWEBENCH_DOCKER_REGISTRY}"
        - name: SWEBENCH_IMAGE_PREFIX
          value: "${SWEBENCH_IMAGE_PREFIX}"
        - name: ENABLE_EXEC
          value: "${ENABLE_EXEC}"
      volumes:
      - name: api-keys
        secret:
          secretName: testbed-api-keys-secret
