---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testbed-api-sa
  namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ${NAMESPACE}
  name: testbed-container-manager
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "get", "delete", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testbed-api-rolebinding
  namespace: ${NAMESPACE}
subjects:
- kind: ServiceAccount
  name: testbed-api-sa
  namespace: ${NAMESPACE}
roleRef:
  kind: Role
  name: testbed-container-manager
  apiGroup: rbac.authorization.k8s.io