apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ${NAMESPACE}
  name: testbed-sidecar-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testbed-sa
  namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testbed-sidecar-rolebinding
  namespace: ${NAMESPACE}
subjects:
- kind: ServiceAccount
  name: testbed-sidecar-sa
  namespace: ${NAMESPACE}
roleRef:
  kind: Role
  name: testbed-sidecar-role
  apiGroup: rbac.authorization.k8s.io
