apiVersion: batch/v1
kind: Job
metadata:
  name: {{ job_name }}
  namespace: {{ namespace }}
  labels:
    testbed-id: {{ testbed_id }}
    user-id: {{ user_id }}
    instance-id: {{ instance_id }}
spec:
  template:
    spec:
      serviceAccountName: testbed-service-account
      containers:
      - name: testbed
        image: {{ testbed_image }}
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sh" ]
        args:
          - -c
          - |
            echo "Starting testbed"
            while true; do
              if [ -f /shared/run_cmd ]; then
                echo "Starting /shared/commands.sh"
                /shared/commands.sh 2>&1 | tee /shared/cmd_output.txt
                rm /shared/run_cmd
                touch /shared/complete_cmd
                echo "Finished /shared/commands.sh"
              elif [ -f /shared/kill ]; then
                echo "Kill command received. Exiting."
                exit 0
              fi
              sleep 1
            done
        resources:
          requests:
            cpu: "{{ request_cpu }}"
            memory: "{{ request_memory }}"
          limits:
            cpu: "{{ limit_cpu }}"
            memory: "{{ limit_memory }}"
        volumeMounts:
        - name: shared-volume
          mountPath: /shared
      - name: sidecar
        image: {{ sidecar_image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: shared-volume
          mountPath: /shared
        env:
        - name: HTTP_PORT
          value: "8000"
        - name: KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: USER_ID
          value: "{{ user_id }}"
        - name: INSTANCE_ID
          value: "{{ instance_id }}"
        - name: TESTBED_ID
          value: "{{ testbed_id }}"
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: testbed-secrets
              key: AZURE_STORAGE_CONNECTION_STRING
      nodeSelector:
        pool: testbed-dev
      restartPolicy: OnFailure
      volumes:
      - name: shared-volume
        emptyDir: {}
  backoffLimit: 4