apiVersion: v1
kind: Service
metadata:
  name: {{ testbed_id }}
  namespace: {{ namespace }}
spec:
  selector:
    job-name: {{ testbed_id }}
  type: LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
